"""Add image_filename to Instance

Revision ID: 27a0d4707979
Revises: a8703386be36
Create Date: 2025-12-12 15:36:55.236950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a0d4707979'
down_revision: Union[str, Sequence[str], None] = 'a8703386be36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('image_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'image_filename')
    # ### end Alembic commands ###
